import {Injectable} from '@angular/core';

@Injectable()
export class AtmTablesService {

  smartTableData = [
    {
        "id": 14,
        "type": "OFFICE",
        "name": "LAS PALMAS DE GRAN CANARIA-FRANCHY ROCA",
        "address": "Avenida Escaleritas, S/N",
        "postalCode": "35007",
        "phone": "928266196",
        "longitude": -15.4363,
        "latitude": 28.1235,
        "bank": "Banco Santander",
        "halcash": true,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 13,
        "type": "OFFICE",
        "name": "SANTA CRUZ DE TENERIFE",
        "address": "Calle Puerta Canseco, 73",
        "postalCode": "38003",
        "phone": "922151198",
        "longitude": -16.255,
        "latitude": 28.4671,
        "bank": "Kutxabank",
        "halcash": false,
        "ingress": true,
        "changePin": false
    },
    {
        "id": 27,
        "type": "OFFICE",
        "name": "CADIZ",
        "address": "Plaza San Juan de Dios, 16",
        "postalCode": "11006",
        "phone": "956808280",
        "longitude": -6.2924,
        "latitude": 36.53,
        "bank": "BBVA",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 31,
        "type": "OFFICE",
        "name": "MÁLAGA-AV.ANDALUCÍA, 19",
        "address": "Avenida Andalucía, S/N",
        "postalCode": "29002",
        "phone": "952041880",
        "longitude": -4.4323,
        "latitude": 36.717,
        "bank": "ING Direct",
        "halcash": true,
        "ingress": true,
        "changePin": false
    },
    {
        "id": 25,
        "type": "OFFICE",
        "name": "ALMERIA",
        "address": "Calle Torres, 11",
        "postalCode": "04001",
        "phone": "950282582",
        "longitude": -2.4654,
        "latitude": 36.8399,
        "bank": "Bankinter",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 29,
        "type": "OFFICE",
        "name": "GRANADA",
        "address": "Calle Gran Vía de Colón, 26",
        "postalCode": "18010",
        "phone": "958207310",
        "longitude": -3.5988,
        "latitude": 37.1784,
        "bank": "Banco Sabadell",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 30,
        "type": "OFFICE",
        "name": "HUELVA",
        "address": "Avenida Tomás Domínguez Ortiz, 4",
        "postalCode": "21001",
        "phone": "959541766",
        "longitude": -6.956,
        "latitude": 37.2538,
        "bank": "BBK",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 32,
        "type": "OFFICE",
        "name": "SEVILLA-VIRGEN DE LUJAN",
        "address": "Calle Virgen de Luján, 39B",
        "postalCode": "41011",
        "phone": "954280487",
        "longitude": -6.0014,
        "latitude": 37.3745,
        "bank": "Banco Santander",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 33,
        "type": "OFFICE",
        "name": "SEVILLA-SAN FRANCISCO JAVIER",
        "address": "Avenida San Francisco Javier, 1",
        "postalCode": "41005",
        "phone": "954660611",
        "longitude": -5.9731,
        "latitude": 37.3825,
        "bank": "La Caixa",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 28,
        "type": "OFFICE",
        "name": "CORDOBA",
        "address": "Avenida Ronda de los Tejares, 10",
        "postalCode": "14001",
        "phone": "957474744",
        "longitude": -4.7805,
        "latitude": 37.8889,
        "bank": "Bankia",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 48,
        "type": "OFFICE",
        "name": "MURCIA-GRAN VÍA ESCULTOR FRANCISCO SALZILLO, 2",
        "address": "Calle Tomás Maestre, 2",
        "postalCode": "30004",
        "phone": "968 98 80 00",
        "longitude": -1.1314,
        "latitude": 37.9836,
        "bank": "Banco Santander",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 41,
        "type": "OFFICE",
        "name": "ALICANTE/ALACANT-FEDERICO SOTO",
        "address": "Avenida Federico Soto, 11",
        "postalCode": "03003",
        "phone": "965210122",
        "longitude": -0.4902,
        "latitude": 38.3448,
        "bank": "Banco Santander",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 26,
        "type": "OFFICE",
        "name": "BADAJOZ",
        "address": "Avenida de Europa, 10",
        "postalCode": "06004",
        "phone": "924200497",
        "longitude": -6.973,
        "latitude": 38.8736,
        "bank": "Banco Santander",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 44,
        "type": "OFFICE",
        "name": "VALENCIA-AV.FRANCIA",
        "address": "Avenida Francia, 32",
        "postalCode": "46023",
        "phone": "963308319",
        "longitude": -0.3478,
        "latitude": 39.4591,
        "bank": "Banco Santander",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 46,
        "type": "OFFICE",
        "name": "VALENCIA-AYUNTAMIENTO",
        "address": "Plaza del Ayuntamiento, 26",
        "postalCode": "46002",
        "phone": "963529517",
        "longitude": -0.3763,
        "latitude": 39.4691,
        "bank": "Banco Santander",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 45,
        "type": "OFFICE",
        "name": "VALENCIA-PIO XII",
        "address": "Avenida Pío XII, S/N",
        "postalCode": "46015",
        "phone": "963455091",
        "longitude": -0.3937,
        "latitude": 39.482,
        "bank": "NG Direct",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 47,
        "type": "OFFICE",
        "name": "VALENCIA-BENIMACLET",
        "address": "AV. POETA EMILIO BARO, 88",
        "postalCode": "46020",
        "phone": "963627152",
        "longitude": -0.359,
        "latitude": 39.4912,
        "bank": "NG Direct",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 43,
        "type": "OFFICE",
        "name": "PALMA DE MALLORCA-SANT MIQUEL",
        "address": "Carrer Sant Miquel, 66",
        "postalCode": "07002",
        "phone": "971713171",
        "longitude": 2.6525,
        "latitude": 39.5765,
        "bank": "NG Direct",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 42,
        "type": "OFFICE",
        "name": "CASTELLON DE LA PLANA-CARDONA VIVES",
        "address": "Calle Mayor, 45",
        "postalCode": "12001",
        "phone": "964232211",
        "longitude": -0.0362,
        "latitude": 39.986,
        "bank": "NG Direct",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 12,
        "type": "OFFICE",
        "name": "FUENLABRADA",
        "address": "Calle de Portugal, 34",
        "postalCode": "28945",
        "phone": "916490192",
        "longitude": -3.8092,
        "latitude": 40.2817,
        "bank": "NG Direct",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 49,
        "type": "OFFICE",
        "name": "GETAFE",
        "address": "Calle Toledo, 5",
        "postalCode": "28901",
        "phone": "901911901",
        "longitude": -3.7323,
        "latitude": 40.3046,
        "bank": "NG Direct",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 9,
        "type": "OFFICE",
        "name": "MADRID-ATOCHA",
        "address": "Paseo de Santa María de la Cabeza, 44",
        "postalCode": "28045",
        "phone": "915395800",
        "longitude": -3.6971,
        "latitude": 40.4037,
        "bank": "NG Direct",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 10,
        "type": "OFFICE",
        "name": "MADRID-CONDE DE CASAL",
        "address": "AV. DOCTOR ESQUERDO, 163",
        "postalCode": "28007",
        "phone": "915014440",
        "longitude": -3.6699,
        "latitude": 40.4081,
        "bank": "NG Direct",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 11,
        "type": "OFFICE",
        "name": "MADRID-LA LATINA",
        "address": "Plaza de la Cebada, 6",
        "postalCode": "28005",
        "phone": "913640786",
        "longitude": -3.7095,
        "latitude": 40.4115,
        "bank": "NG Direct",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 1,
        "type": "OFFICE",
        "name": "MADRID-SERRANO",
        "address": "Calle de Serrano, 62",
        "postalCode": "28001",
        "phone": "915866035",
        "longitude": -3.6872,
        "latitude": 40.4292,
        "bank": "BBVA",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 4,
        "type": "OFFICE",
        "name": "MADRID-ALBERTO AGUILERA",
        "address": "Calle de Alberto Aguilera, 46",
        "postalCode": "28015",
        "phone": "915489123",
        "longitude": -3.712,
        "latitude": 40.4303,
        "bank": "BBVA",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 5,
        "type": "OFFICE",
        "name": "MADRID-ARTURO SORIA",
        "address": "Calle de Arturo Soria, 36",
        "postalCode": "28027",
        "phone": "913682286",
        "longitude": -3.6404,
        "latitude": 40.4416,
        "bank": "BBVA",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 2,
        "type": "OFFICE",
        "name": "MADRID-ARAVACA/POZUELO",
        "address": "Avenida de Europa, 30B",
        "postalCode": "28023",
        "phone": "913515455",
        "longitude": -3.7844,
        "latitude": 40.4448,
        "bank": "BBVA",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 6,
        "type": "OFFICE",
        "name": "MADRID-CASTELLANA/CUZCO",
        "address": "Calle del Capitán Haya, 36",
        "postalCode": "28020",
        "phone": "915701550",
        "longitude": -3.6918,
        "latitude": 40.4596,
        "bank": "BBVA",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 8,
        "type": "OFFICE",
        "name": "ALCALÁ DE HENARES",
        "address": "Vía Complutense, S/N",
        "postalCode": "28805",
        "phone": "918819648",
        "longitude": -3.3615,
        "latitude": 40.4862,
        "bank": "BBVA",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 3,
        "type": "OFFICE",
        "name": "LAS ROZAS DE MADRID",
        "address": "Calle Real, S/N",
        "postalCode": "28231",
        "phone": "916372162",
        "longitude": -3.8717,
        "latitude": 40.4914,
        "bank": "BBVA",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 7,
        "type": "OFFICE",
        "name": "ALCOBENDAS-SAN SEBASTIÁN DE LOS REYES",
        "address": "Plaza Henry Dunnat, S/N",
        "postalCode": "28100",
        "phone": "916573822",
        "longitude": -3.6294,
        "latitude": 40.5437,
        "bank": "Banco Sabadell",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 20,
        "type": "OFFICE",
        "name": "SALAMANCA",
        "address": "Calle Zamora, 24",
        "postalCode": "37002",
        "phone": "923217100",
        "longitude": -5.664,
        "latitude": 40.9665,
        "bank": "Banco Sabadell",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 40,
        "type": "OFFICE",
        "name": "TARRAGONA-PERE MARTELL",
        "address": "Carrer Pere Martell, 48",
        "postalCode": "43005",
        "phone": "977958998",
        "longitude": 1.2434,
        "latitude": 41.1132,
        "bank": "Banco Sabadell",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 36,
        "type": "OFFICE",
        "name": "L'HOSPITALET DE LLOBREGAT",
        "address": "CL. ENRIC PRAT DE LA RIBA, 165",
        "postalCode": "08901",
        "phone": "933371300",
        "longitude": 2.1085,
        "latitude": 41.3622,
        "bank": "Banco Sabadell",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 37,
        "type": "OFFICE",
        "name": "BARCELONA-GRAN VIA DE LES CORTS CATALANES, 509",
        "address": "Gran Via de les Corts Catalanes, S/N",
        "postalCode": "08015",
        "phone": "934533718",
        "longitude": 2.1574,
        "latitude": 41.3815,
        "bank": "Banco Sabadell",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 38,
        "type": "OFFICE",
        "name": "BARCELONA-DIAGONAL",
        "address": "Avinguda de Sarrià, S/N",
        "postalCode": "08029",
        "phone": "935212778",
        "longitude": 2.1392,
        "latitude": 41.3912,
        "bank": "Bankia",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 39,
        "type": "OFFICE",
        "name": "BARCELONA-TETUAN",
        "address": "Plaça de Tetuán, 19",
        "postalCode": "08010",
        "phone": "932652621",
        "longitude": 2.1746,
        "latitude": 41.3952,
        "bank": "Bankia",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 34,
        "type": "OFFICE",
        "name": "BADALONA",
        "address": "CL. LAIETANIA, 1-11 ESQ.PRESID.COMPANYS",
        "postalCode": "08911",
        "phone": "933842460",
        "longitude": 2.2483,
        "latitude": 41.4535,
        "bank": "Bankia",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 35,
        "type": "OFFICE",
        "name": "SABADELL",
        "address": "Carrer de Narcís Giralt, 29",
        "postalCode": "08202",
        "phone": "937254744",
        "longitude": 2.1108,
        "latitude": 41.5457,
        "bank": "Bankia",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 22,
        "type": "OFFICE",
        "name": "VALLADOLID-GAMAZO",
        "address": "Calle Gamazo, 20",
        "postalCode": "47004",
        "phone": "983375050",
        "longitude": -4.7262,
        "latitude": 41.6459,
        "bank": "Bankia",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 24,
        "type": "OFFICE",
        "name": "ZARAGOZA-PUERTA DEL CARMEN",
        "address": "Avenida César Augusto, S/N",
        "postalCode": "50004",
        "phone": "976212202",
        "longitude": -0.8874,
        "latitude": 41.6498,
        "bank": "La Caixa",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 16,
        "type": "OFFICE",
        "name": "BURGOS-CID CAMPEADOR",
        "address": "Calle Petronila Casado, S/N",
        "postalCode": "09004",
        "phone": "947252591",
        "longitude": -3.6973,
        "latitude": 42.3463,
        "bank": "La Caixa",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 18,
        "type": "OFFICE",
        "name": "LOGROÑO-MIGUEL VILLANUEVA",
        "address": "Calle Miguel Villanueva, 5",
        "postalCode": "26001",
        "phone": "941254337",
        "longitude": -2.4459,
        "latitude": 42.4641,
        "bank": "La Caixa",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 19,
        "type": "OFFICE",
        "name": "PAMPLONA/IRUÑA",
        "address": "Avenida de Carlos III El Noble, 53",
        "postalCode": "31004",
        "phone": "948247600",
        "longitude": -1.6374,
        "latitude": 42.8117,
        "bank": "La Caixa",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 15,
        "type": "OFFICE",
        "name": "VITORIA/GASTEIZ",
        "address": "Calle Ramón Ortiz de Zárate, 8",
        "postalCode": "01005",
        "phone": "945143630",
        "longitude": -2.6697,
        "latitude": 42.8434,
        "bank": "Kutxabank",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 23,
        "type": "OFFICE",
        "name": "BILBAO-ALAMEDA DE URQUIJO",
        "address": "Alameda Urquijo, 25",
        "postalCode": "48008",
        "phone": "944430088",
        "longitude": -2.9334,
        "latitude": 43.2596,
        "bank": "Kutxabank",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 17,
        "type": "OFFICE",
        "name": "SAN SEBASTIAN/DONOSTIA",
        "address": "Avenida de la Libertad, 2",
        "postalCode": "20004",
        "phone": "943423989",
        "longitude": -1.9797,
        "latitude": 43.3206,
        "bank": "Kutxabank",
        "halcash": false,
        "ingress": false,
        "changePin": false
    },
    {
        "id": 21,
        "type": "OFFICE",
        "name": "SANTANDER",
        "address": "Calle Hernán Cortés, 15",
        "postalCode": "39003",
        "phone": "942319042",
        "longitude": -3.8032,
        "latitude": 43.4627,
        "bank": "Kutxabank",
        "halcash": false,
        "ingress": false,
        "changePin": false
    }
];

  getData(): Promise<any> {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve(this.smartTableData);
      }, 2000);
    });
  }
}
